# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10)),
                ('product_name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('specification', models.TextField()),
                ('stock', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('sale', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
