# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 16:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 3, 14, 16, 26, 23, 843457, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
