db:
    image: postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: django_seed
vendors:
    image: python:3.5
    working_dir: /code
    volumes:
        - .:/code
    environment:
        PYTHONUSERBASE: /code/vendors/
        PROJECTNAME: django_seed
    command: bash /code/vendor_container_init.sh
web:
    image: python:3.5
    working_dir: /code
    volumes:
        - .:/code
    ports: 
        - "8000:8000"
    environment:
        PYTHONUNBUFFERED: 1
        PYTHONUSERBASE: /code/vendors/
    command: python manage.py runserver 0.0.0.0:8000                
    links:
        - db