version: '2'
services:
    db:
        image: postgres
    vendors:
        build: .
        working_dir: /code
        volumes:
            - .:/code
        environment:
            PYTHONUSERBASE: /code/vendors
        command: pip install -r requirements.txt --user --upgrade    
    web:
        build: .
        working_dir: /code
        volumes:
            - .:/code
        ports: 
            - "8000:8000"
        environment:
            PYTHONUNBUFFERED: 1
            PYTHONUSERBASE: /code/vendors
        command: python manage.py runserver 0.0.0.0:8000
        links:
            - db